### ISSUE TITLE
Unable to get themes to work on story components

### ISSUE THREAD

**Issue by justin-peterson-jdas** [react-theming/storybook-addon-material-ui#116]
Hey there, I cannot for the life of me get this add on to work. I am using TypeScript, MUI 4, with Storybook 5.2.8 and CSF instead of the storybook API. I'm also using the addon globally instead of on individual stories, although I tried running it at the story level with the storiesOf API and no luck. I believe the issue is related to the library using [MUIThemeProvider as opposed to ThemeProvider](https://material-ui.com/customization/theming/) when wrapping the stories. Here's what I have setup: 

config.js
```
import { configure } from '@storybook/react';
import { addDecorator } from '@storybook/react';
import {DarkTheme, LightTheme, HighContrastTheme} from '@jda/lui-component-library'
import { muiTheme } from 'storybook-addon-material-ui';

addDecorator(muiTheme([DarkTheme, LightTheme, HighContrastTheme]));

configure(require.context('../src', true, /\.stories\.tsx?$/), module)
```

addon.js
```
import 'storybook-addon-material-ui/register';
```
button.stories.tsx
```
import * as React from 'react';
import { Button } from "@material-ui/core";

export default { 
    title: 'JDA|LUI/Button',
    component: Button
 };

export const themedButtons = () => (
    <div>
        <Button variant="contained" color="primary">Button</Button>
    </div>    
)
```

Now the panel renders and I can select my themes, but my button doesn't actually change themes:
![image](https://user-images.githubusercontent.com/58446641/71842469-960e1180-3076-11ea-9fd9-a33b3421d281.png)

Any thoughts?

**Comment by mayteio** [comment]
Same issue here. Would be awesome to be able to toggle them.

**Comment by JanineLourens** [comment]
Bump I have the same problem. Would really like some solution

**Comment by mayteio** [comment]
[I built a super lightweight version](https://github.com/mayteio/storybook-addon-materialui/blob/master/README.md) of this add on - just pass your themes in and toggle with a dropdown 👍

**Comment by JanineLourens** [comment]
@mayteio Thanks!!! It doesn't have all the features that I want,  like color selection but this is already a great compromise <3 <3 <3

**Comment by UsulPro** [comment]
Thanks @mayteio 

Also any PRs with improvements to this project are always welcome!

**Comment by mayteio** [comment]
All good - if I have a moment I’ll see if I can get something similar working in this package. I just wanted to wrap my themes rather than build them in storybook for an internal component library - branding and colours are already set.

**Comment by justin-peterson-jdas** [comment]
@mayteio awesome man, nice addon :) This is exactly what I was going to do. I'm going to see if I can just utilize yours instead

**Comment by yatrix7** [comment]
> [I built a super lightweight version](https://github.com/mayteio/storybook-addon-materialui/blob/master/README.md) of this addon - that solves my problem above. Just pass your themes in and toggle with a dropdown 👍

Worked the first time I tried it. Well done.

**Comment by vvetsko** [comment]
Had the same problem, but is ok when passing ThemeOptions instead of Theme into muiTheme decorator. 

The issue still exists, as I am using typescript and should add an exception for this (

**Comment by UsulPro** [comment]
@vvetsko can we update https://github.com/react-theming/storybook-addon-material-ui/blob/version-1/storybook-addon-material-ui.d.ts to add the exception?

**Comment by Moonachi** [comment]
I have same issue. Has the issue been resolved?

**Comment by UsulPro** [comment]
Hey here!

First of all sorry for the inconvenience and thank you for your patience :smile_cat: 

While developing of stable version of this addon is in progress and you're looking for just a simple functionality, you can switch to another one:
https://github.com/react-theming/storybook-addon-theming

It's an universal one and don't have Material-UI specific features, but you can use it when switching themes and changing colors is enough for your case

[demo](https://react-theming.github.io/theming-material-ui/)

```sh
yarn add --dev @react-theming/storybook-addon
```

to use it with Material UI you'll need to pass theme provider into decorator this way:

```js
import { withThemes } from '@react-theming/storybook-addon';
import { ThemeProvider } from '@material-ui/core';
import { createMuiTheme } from '@material-ui/core/styles';

import theme from '../theme';

const providerFn = ({ theme, children }) => {
  const serialTheme = JSON.parse(JSON.stringify(theme));
  const muTheme = createMuiTheme(serialTheme);
  return <ThemeProvider theme={muTheme}>{children}</ThemeProvider>;
};

export default {
  title: 'MUI Examples',
  component: Component,
  decorators: [withThemes(null, [theme], { providerFn })],
};

```

or see details in the template project https://github.com/react-theming/theming-material-ui
