### ISSUE TITLE
The addition of new objects to themes

### ISSUE THREAD

**Issue by UsulPro** [react-theming/storybook-addon-material-ui#12]
We can add any properties and objects to `theme` manually to JSON string in `Panel`
It would also be good to add objects by mouse in the `sidebar` editor

Starting point is here:
[src/components/ThemeSideBar](https://github.com/sm-react/storybook-addon-material-ui/blob/master/src/components/ThemeSideBar.js)

**Comment by dantesolis** [comment]
Hey guys,  may be a stupid question, but is this a good *1st time contributor* issue? Thinking about tackling it.

Thanks

**Comment by UsulPro** [comment]
Hi @dantesolis! I think this is simple enough. And you always welcome to ask questions. Perhaps it will be easier to start with this https://github.com/sm-react/storybook-addon-material-ui/issues/11. It's the same but adding new properties to already existing objects. Pay attention to the material design and design of this app, please.

**Comment by UsulPro** [comment]
Perhaps it worth to review after switching to v1. Closing now
