### ISSUE TITLE
Support Storybook v6.1

### ISSUE THREAD

**Issue by sarahannnicholson** [react-theming/storybook-addon-material-ui#121]
Trying to add this wonderful package to our repo. 

`npm i -D storybook-addon-styled-component-theme`

And I get this back:
> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: [my_package_name@my_version]
npm ERR! Found: @storybook/addons@6.1.7
npm ERR! node_modules/@storybook/addons
npm ERR!   dev @storybook/addons@"^6.1.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/addons@"^5.2.0" from storybook-addon-styled-component-theme@1.3.0
npm ERR! node_modules/storybook-addon-styled-component-theme
npm ERR!   dev storybook-addon-styled-component-theme@"*" from the root project     
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.     
npm ERR!
npm ERR! See /home/[my_user]/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/[my_user]/.npm/_logs/2020-11-27T00_27_57_440Z-debug.log

I can see in this package.json for this addon the peerDependencies dont include version 6. So I'm assuming the support needs to be added?

Some other useful info:
node -v: `v15.3.0`
npm -v: `7.0.14`
Storybook version: `6.1.7`

**Comment by Rondip** [comment]
Can we have an update on this?

**Comment by UsulPro** [comment]
Hey guys! released alpha.22. Let me know if it works fine with Storybook 6?

**Comment by sarahannnicholson** [comment]
Hey! works for me! I have a pretty basic use case for it, so maybe I'm not the best person to ask for about edge cases and such. 

Thanks so much for updating to storybook 6.1 support! I tried to do it myself in a fork but didn't get it to the point I wanted to make a PR. Really appreciate the update! Thanks so much :)
