### ISSUE TITLE
Material-ui V5 (next)

### ISSUE THREAD

**Issue by Boimb** [react-theming/storybook-addon-material-ui#129]
Hi,
Nice job you've done there!
Since I'm using the next version of Material-ui, there are some breaking changes that make this add-on _deprecated_. (The ThemeProvider mainly)
I don't see that much more activity up there, so I was wondering if you where still active, and if you planed to be V5 (aka next for now) compliant.

I could try a PR if it may be merged.
Just let me now where you're at and if this kind of contribution is still possible.
Regards.
Boimb.

**Comment by UsulPro** [comment]
Hey @Boimb Thanks!
This addon isn't deprecated but doesn't actively developed. PRs are always welcome but probably you could consider using this addon istead https://github.com/react-theming/storybook-addon#using-with-material-ui this one is more universal and also has support for Material-UI. Potenitially in a future we'll switch the core of storybook-addon-material-ui to this one

**Comment by Boimb** [comment]
Hi @UsulPro Did not find this one. Thx. Gonna take a look at it. 
keep up the good work.
