### ISSUE TITLE
Demo Page 404

### ISSUE THREAD

**Issue by appjitsu** [react-theming/storybook-addon-material-ui#61]
From the README link:

https://sm-react.github.io/react-theming/?theme-ind=0&theme-sidebar=true&theme-full=true&knob-Title=Welcome%20to%20React-Theming&knob-Subtitle=Storybook%20Boilerplate%20Project&selectedKind=Material-UI&selectedStory=Components&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel

**Comment by UsulPro** [comment]
@appjitsu Thank you for reporting this!
Now it's fixed!
