### ISSUE TITLE
Remove react-tap-event-plugin dependency

### ISSUE THREAD

**Issue by MOZGIII** [react-theming/storybook-addon-material-ui#65]
Material UI 0.19 removed deoendency to `react-tap-event-plugin` to provide support for React 16. This package should get rid of it too and update to Material UI 0.19+.

**Comment by UsulPro** [comment]
Thanks @MOZGIII

**Comment by UsulPro** [comment]
Done in [0.8.1](https://github.com/react-theming/storybook-addon-material-ui/releases/tag/0.8.1)
