### ISSUE TITLE
<IconButton iconClassName="muidocs-icon-custom-github" />

### ISSUE THREAD

**Issue by philipbeadle** [react-theming/storybook-addon-material-ui#69]
hey, thanx for this add-on, very cool.  Is there a way to use the IconButton?  I cant figure it out.

Cheers

**Comment by UsulPro** [comment]
Hi, @philipbeadle, thank you!

What kind of issues do you have with IconButton?

**Comment by philipbeadle** [comment]
I can't get the icon to show.  The button is there and I can pout text in it to show it but no icon shows.  

In the boilerplate project I added the import for IconButton and then switched the first FlatButton on ComponentsExample.jsx to

<IconButton iconClassName="muidocs-icon-custom-github" />

In the StoryBook the button is clickable but no icon shows.

Love to know what I missed :)

Cheers

**Comment by UsulPro** [comment]
closing, since not active
