### ISSUE TITLE
Peer dependency warning when using v4 alpha

### ISSUE THREAD

**Issue by Snaptags** [react-theming/storybook-addon-material-ui#75]
I am using storybook v4.0.0-alpha.9 to solve compatibility problems with webpack. But the material-ui addon keeps complaining that it requires a peer of @storybook/react@^3.0.0.

**Comment by UsulPro** [comment]
Hi @Snaptags
previous versions of this addon didn't work with Storybook `v4.0.0-alpha.xx` 
Now I published `storybook-addon-material-ui@0.8.9` which is compatible

**Comment by Snaptags** [comment]
Actually there are TWO warnings now:
![warning](https://user-images.githubusercontent.com/1249745/42151707-22fc43f2-7dde-11e8-9bc1-5a637a9df98e.png)

**Comment by UsulPro** [comment]
hm... possible it's because `4.0.0-alpha.10` don't fit `^4.0.0`? 
Do you want to make PR to fix it?
