### ISSUE TITLE
Cannot read property 'prepareStyles' of undefined

### ISSUE THREAD

**Issue by llmdev** [react-theming/storybook-addon-material-ui#78]
I made all the configuration that is here but it returns me this error

> Cannot read property 'prepareStyles' of undefined

**Comment by UsulPro** [comment]
Hi @llmdev !
Could you please give me a bit more information about this error? Does it happen on a specific story?

**Comment by llmdev** [comment]
Yes it happens in a specific story,

`import React from 'react';
import { storiesOf } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import { action } from '@storybook/addon-actions';
import { muiTheme } from 'storybook-addon-material-ui';



import StepPanel from '@/components/StepPanel/StepPanel';
import { createMuiTheme } from '@material-ui/core/styles'; // v1.x
import { Kestraa } from '@/lib/palette';

const customTheme1 = createMuiTheme({
  palette: {
      primary: {
          light: '#c0c',
          main: '#c0c',
          dark: '#ccc',
          contrastText: '#fff',
      },
      secondary: {
          light: '#c0c',
          main: '#c0c',
          dark: '#c0c',
          contrastText: '#fff',
      },
  },
  themeName: 'Custom Light Theme',
});


storiesOf('StepPanel', module)
  .addDecorator(
    muiTheme([customTheme1]),
  )
  .add('Default', withInfo(`
    Step Panel default implementation.
  `)(
    () => (
      <StepPanel 
        step={1}
        stepName="Panel"
        onExpansionClick={action('on-expansion-click')}
        currentExpandedPanel="panel"
        panelName="panel"
        onNext={action('on-next')}
      >
        Content
      </StepPanel>
    ),
  ))
  .add('With Save', withInfo(`
    Step Panel with save button implementation.
  `)(
    () => (
      <StepPanel
        step={1}
        stepName="Panel"
        onExpansionClick={action('on-expansion-click')}
        currentExpandedPanel="panel"
        panelName="panel"
        onSave={action('on-save')}
        lastPanel
      >
        Content
      </StepPanel>
    ),
  ))
  .add('Not Expanded', withInfo(`
    Step Panel not expanded implementation.
  `)(
    () => (
      <StepPanel
        step={1}
        stepName="Panel"
        onExpansionClick={action('on-expansion-click')}
        currentExpandedPanel={null}
        panelName="panel"
        onNext={action('on-next')}
      >
        Content
      </StepPanel>
    ),
  ));
`

**Comment by UsulPro** [comment]
could you clarify what version of `storybook-addon-material-ui` do you use?

**Comment by llmdev** [comment]
"storybook-addon-material-ui": "^0.9.0-alpha.8",

**Comment by llmdev** [comment]
Warning: Failed prop type: Invalid prop `themesInitList` of type `array` supplied to `MuiTheme`, expected `function`.
    in MuiTheme

**Comment by UsulPro** [comment]
happy to know it!
good luck
