### ISSUE TITLE
Wrong PropType

### ISSUE THREAD

**Issue by snaumov** [react-theming/storybook-addon-material-ui#79]
Hi,

getting small propType warning

> Warning: Failed prop type: Invalid prop `themesInitList` of type `array` supplied to `MuiTheme`, expected `function`.
    in MuiTheme

Got the same results on fresh repo.

**Comment by UsulPro** [comment]
Hi @snaumov, what version of addon do you use?

**Comment by snaumov** [comment]
@UsulPro the latest, 0.9.0-alpha.8

**Comment by UsulPro** [comment]
@snaumov thanks for reporting, I'll check it and fix with the next release

**Comment by gemscng** [comment]
@UsulPro Thanks for your great work. Just wondering when will be the next release?

**Comment by agentlewis** [comment]
Just to add that I am getting this error when calling `addDecorator(muiTheme([MyCustomTheme]))` in config.js

MyCustomTheme is the result of `createMuiTheme`

Thanks!
D

**Comment by UsulPro** [comment]
@agentlewis Thanks, Guys! I hope next release will be in 1-2 weeks

**Comment by UsulPro** [comment]
[0.9.0-alpha.14](https://github.com/react-theming/storybook-addon-material-ui/releases/tag/0.9.0-alpha.14) is released. It exposes new functionality and bug fixes
