### ISSUE TITLE
Upgrading Babel to 7.0.0

### ISSUE THREAD

**Issue by agentlewis** [react-theming/storybook-addon-material-ui#82]
I am having trouble upgrading to version `v4.0.0-alpha.20` of storybook from `v4.0.0-alpha.16`

I think it is something to do with babel versions. As soon as I upgrade I start getting errors relating to missing polyfills in material-ui. This confused me as material also now uses babel 7 (not that it should matter...) 

So I wondered if it might be that the addon is somehow the culprit - I haven't yet verified this. My next step is to try and start a new project from scratch and see if I can replicate the issue.

I just wanted to post this here to see if you may know something about this?

**Comment by UsulPro** [comment]
@agentlewis Thank you for reporting this! I didn't try the addon with the latest alpha yet. Please, let me know if you dig something more. I'll try to check it as well!

**Comment by UsulPro** [comment]
@agentlewis I managed to run `@storybook/react@4.0.0-alpha.21` with `storybook-addon-material-ui@0.9.0-alpha.8` in CRA
You can try this config from https://github.com/react-theming/create-material-ui-app

**Comment by UsulPro** [comment]
I guess I can close it since the latest versions work fine with the babel v7 
But please reopen it if you still have any issues with that
