### ISSUE TITLE
theme editor still support?

### ISSUE THREAD

**Issue by pohsiu** [react-theming/storybook-addon-material-ui#83]
as title 
I notice that 0.9.0 alpha8 didn't support theme editor like demo's page,
how to use it?

![image](https://user-images.githubusercontent.com/3203630/45073654-d839e280-b112-11e8-9217-63f4b51470bf.png)

**Comment by UsulPro** [comment]
@pohsiu v1 will have a bit another way to manage color. Still with color picker but without Sidebar since it was created for Storybook v1 and a lot has changed since then.
I guess this functionality will be restored in one of the nearest releases

**Comment by UsulPro** [comment]
@pohsiu check out the latest alpha. It restores the color picker functionality
I'm closing this for now, but feel free to leave any comments related to this question
