### ISSUE TITLE
after upgrade alpha-15 from alpha-14 

### ISSUE THREAD

**Issue by pohsiu** [react-theming/storybook-addon-material-ui#85]
![image](https://user-images.githubusercontent.com/3203630/45603918-b10fd900-ba61-11e8-80e1-dee12cb79f7e.png)

After upgrading, I got this error.

**Comment by tlenex** [comment]
Same here, happens with storybook ^3.4.10

**Comment by UsulPro** [comment]
oops, didn't provide compatibility with previous versions
now fixed in alpha-16
sorry for the inconvenience, guys!
