### ISSUE TITLE
Crash when moving mouse over color palette in Material UI tab

### ISSUE THREAD

**Issue by tlenex** [react-theming/storybook-addon-material-ui#86]
![Image with error](https://i.imgur.com/G8uvf8s.png)
Occurs when moving mouse cursor over main color palette.
After that, the Material UI tab becomes blank and error from the image bumps up in the console.

Version: 0.9.0-alpha.16
Storybook: 3.4.11

**Comment by UsulPro** [comment]
Thanks for reporting @tlenex 
Hmm... I need to check. What version of Material-UI do you use?

**Comment by UsulPro** [comment]
@tlenex  I can't reproduce it with Storybook 3.4.11, but I hope it will be solved in the next release of addon alongside the other issues

**Comment by tlenex** [comment]
Thanks for heads up @UsulPro . I'll let you know if the issue still occurs. Perhaps this is issue is only present with combination of some other storybook addons, I'll check.

**Comment by tlenex** [comment]
The problem was on my end. 

I did not provide any palette color in my theme, adding it solved this issue. 
I think this could be handled by this plugin in the same way as in material-ui package, providing some defaults.

Closing for now.

**Comment by UsulPro** [comment]
Thanks @tlenex for your reply and sorry for the inconvenience!
I'll check about default themes, it should be considered as a bug if you can't use add on without own settings
