### ISSUE TITLE
Wrong package versions in 'version-1' branch

### ISSUE THREAD

**Issue by GProst** [react-theming/storybook-addon-material-ui#88]
Hey there, hope you're doing well.

We found incorrect versions in your `package.json` in `version-1` branch:
```json
"@babel/plugin-proposal-class-properties": "^7.1.2",
"@babel/preset-react": "^7.1.2"
```
First one has `7.1.0` latest version and the second one `7.0.0`.
This causes our CI to fail due to `yarn` forces to interactively pick the correct version for those packages.

**Comment by UsulPro** [comment]
Hey German, thanks!

Do you want to add PR for fixing this?)

**Comment by GProst** [comment]
Seems like all good now 👍

**Comment by UsulPro** [comment]
Do you need it to be published to npm now?

**Comment by GProst** [comment]
I believe no need for us right now, we fetch it from git branch 'version-1'
