### ISSUE TITLE
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by artemirq** [react-theming/storybook-addon-material-ui#92]
**Describe the bug**

When I upgraded Storybook from `4.0.9` to `5.0.0`, by starting `start-storybook`, I give error (see screenshot below)

**Expected behavior**

Storybook works without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/17342159/53846231-3447cb80-3fbd-11e9-973e-851b465e2952.png)

**System:**
 - OS: `Windows 10`
 - Framework: `React`
 - Addons: `@storybook/addon-actions@5.0.0`, `storybook-addon-material-ui@0.9.0-alpha.17`, `storybook-addon-intl@2.4.0`
 - Version: `5.0.0`

**Additional context**

This error stack doesn't give any information with which file have problem

**Comment by artemirq** [comment]
I think this problem because Storybook 5 Theming has [rewritten](https://github.com/storybooks/storybook/blob/next/MIGRATION.md#theming-overhaul)
@UsulPro Should we expect, that `storybook-addon-material-ui` going support Storybook 5 soon?

**Comment by UsulPro** [comment]
@artemirq thanks for reporting!

Yes, I hope we will support Storybook V5 soon

**Comment by msreekm** [comment]
same error while upgrading to 5.

**Comment by davthu** [comment]
Any status on this issue?

**Comment by UsulPro** [comment]
This is WIP
any help is appreciated as well

**Comment by tlenex** [comment]
It seems that `webpack` in storybook is trying to import `ic_done_white_64dp_1x.png` and `ic_done_black_64dp_1x.png` like the one in `react-material-color-picker` file but instead of transforming the import into url, it get it as string content, which is an binary file, starting with `�` character.

Probably this is caused by some wrong order of loaders in webpack `config`, but im not sure.

**Comment by tlenex** [comment]
Yup, removing those imports from `node_modules/react-material-color-picker/dist/MaterialColorPicker.js` resolves the issue, but the icons are gone. 

For me, `dist` bundle step in `react-material-color-picker` is doing something wrong, it's bundling commonjs with import of .png file, which should be transformed into base64 string or something in the bundling step.

**Comment by tlenex** [comment]
Seems connected to: https://github.com/storybooks/storybook/issues/4995 and #90 .
There is an solution for modifying Manager webpack config: https://github.com/storybooks/storybook/issues/4995#issuecomment-447270973

**Comment by davthu** [comment]
I can confirm that the solution provided by @tlenex works.

**Comment by UsulPro** [comment]
Thank you guys for the help!
Fixed this issue in `alpha-18`
Could you check it please?

**Comment by tlenex** [comment]
After upgrading to `0.9.0-alpha.18` storybook `5.0.6` works for me
