### ISSUE TITLE
Not registering in Storybook panel

### ISSUE THREAD

**Issue by stephenway** [react-theming/storybook-addon-material-ui#93]
I installed this extension running the latest storybook. Once I started it I noticed that the panel for material-ui is missing.

**Comment by simoneb** [comment]
That's because there's an error in the docs. See the [example](https://github.com/react-theming/create-material-ui-app/blob/master/.storybook/addons.js) for the correct addon registration code.

**Comment by UsulPro** [comment]
solved in #94
